site_name: Knowledge Stack
site_url: https://knowledge-stack.kelvinjoson.com
#repo_url: https://github.com/KelvinJoson/knowledge-stack
#repo_name: KelvinJoson/knowledge-stack
site_description: Knowledge-Stack by Kelvin Joson
site_author: Kelvin Joson
copyright: Copyright &copy; 2024 Kelvin Joson

theme:
  font:
    text: Roboto
    code: Roboto Mono
  name: material
  custom_dir: overrides
  icon:
    #logo: material/alpha-k-box
    logo: fontawesome/solid/user-astronaut
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  features:
    - announce.dismiss
    - navigation.tabs
    #- navigation.tabs.sticky
    - header.autohide
    - content.tabs.link
    #- content.action.edit
    #- content.action.view
    - navigation.instant
    - navigation.tracking
    #- navigation.top
    #- navigation.expand
    - search.share
    - search.suggest
    - navigation.indexes
    #- navigation.sections
    - toc.follow
    - toc.integrate

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-5
        name: Switch to Dark Mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to Light Mode

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:kelvin@kelvinjoson.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/kelvinjoson/
    - icon: fontawesome/brands/github
      link: https://github.com/KelvinJoson
    - icon: fontawesome/solid/earth-asia
      link: https://kelvinjoson.com

  analytics:
    provider: google
    property: G-9SYHV8CDG0
  consent:
    title: Cookie consent
    description: >-
      In order to monitor how well my home page is doing and whether visitors find what they are searching for, 
      I use cookies to keep track of your preferences and repeat visits.
      With your consent, you are assisting in improving this website.
markdown_extensions:
  - admonition
  - nl2br
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: ⚑
      baselevel: 1

plugins:
  - tags:
        tags: true
  - search
  - callouts
  - roamlinks
  - social
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
